field.widget.settings.entity_reference_group_by_field_widget:
  type: mapping
  label: 'Entity reference group by field widget widget settings'
  mapping:
    bundle_options:
      type: textfield
      label: 'Which Bundles'
    group_by:
      type: textfield
      label: 'Group by'
