field.widget.settings.group_by_field_reference_widget:
  type: mapping
  label: 'Group by field reference widget widget settings'
  mapping:
    bundle_options:
      type: textfield
      label: 'Which Bundles'
    group_by:
      type: textfield
      label: 'Group by'
    open_details:
      type: boolean
      label: 'Open details by default'
